name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t nodejs_docker:latest .

  deploy:
    runs-on: self-hosted

    steps:
      - name: Delete old container
        run: |
          if (docker ps -a | Select-String "nodejs_docker-container") {
            docker rm -f nodejs_docker-container
          }

      - name: Create .env file
        run: echo "${{ secrets.ENVIRONMENT }}" | iconv -f UTF-16LE -t UTF-8 > .env


      - name: Run Docker container
        run: docker run -d -p 5000:5000 --name nodejs_docker-container --env-file .env nodejs_docker:latest
