name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log into Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker image
        run: docker build -t shailendratrivedi009/nodejs_docker:latest .

      - name: Push Docker image to Docker Hub
        run: docker push shailendratrivedi009/nodejs_docker:latest

  pull:
    runs-on: windows-latest

    steps:
      - name: Log into Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Pull Docker image from Docker Hub
        run: docker pull shailendratrivedi009/nodejs_docker:latest

      - name: Delete old container
        run: docker rm -f nodejs_docker-container || true

      - name:
        run: docker run -d -p 5000:5000 --name nodejs_docker-container shailendratrivedi009/nodejs_docker:latest
